version: '3.4'

services:
  grass-homeservice:
    container_name: grass-homeservicebackend
    hostname: grass-homeservicebackend
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4001:80"
    volumes:
      - /data:/app/Data
    networks:
      - global

networks:
  global:
    external: true